export const shopTypes = {
  // UPDATE_SHOPDATA: "UPDATE_SHOPDATA",
  FETCH_SHOPDATA_PROCESSING: "FETCH_SHOPDATA_PROCESSING",
  FETCH_SHOPDATA_SUCCESS: "FETCH_SHOPDATA_SUCCESS",
  FETCH_SHOPDATA_FAILURE: "FETCH_SHOPDATA_FAILURE",
};
