const cartTypes = {
  TOGGLE_CART_VISIBLE: "TOGGLE_CART_VISIBLE",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REDUCE_CART_ITEM: "REDUCE_CART_ITEM",
  CLEAR_CART_ITEM: "CLEAR_CART_ITEM",
  CLEAR_ALL_CART: "CLEAR_ALL_CART",
  CLEAR_ALL_CART_ACTION: "CLEAR_ALL_CART_ACTION",
};

export default cartTypes;
